# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hash-seeds.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hash-seeds.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10hash-seeds.proto\"<\n\x08HashSeed\x12\r\n\x05seed1\x18\x01 \x02(\x04\x12\r\n\x05seed2\x18\x02 \x02(\x04\x12\x12\n\nexpiryDate\x18\x03 \x02(\x04\"%\n\tHashSeeds\x12\x18\n\x05seeds\x18\x01 \x03(\x0b\x32\t.HashSeed')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HASHSEED = _descriptor.Descriptor(
  name='HashSeed',
  full_name='HashSeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seed1', full_name='HashSeed.seed1', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seed2', full_name='HashSeed.seed2', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expiryDate', full_name='HashSeed.expiryDate', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=80,
)


_HASHSEEDS = _descriptor.Descriptor(
  name='HashSeeds',
  full_name='HashSeeds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seeds', full_name='HashSeeds.seeds', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=119,
)

_HASHSEEDS.fields_by_name['seeds'].message_type = _HASHSEED
DESCRIPTOR.message_types_by_name['HashSeed'] = _HASHSEED
DESCRIPTOR.message_types_by_name['HashSeeds'] = _HASHSEEDS

HashSeed = _reflection.GeneratedProtocolMessageType('HashSeed', (_message.Message,), dict(
  DESCRIPTOR = _HASHSEED,
  __module__ = 'hash_seeds_pb2'
  # @@protoc_insertion_point(class_scope:HashSeed)
  ))
_sym_db.RegisterMessage(HashSeed)

HashSeeds = _reflection.GeneratedProtocolMessageType('HashSeeds', (_message.Message,), dict(
  DESCRIPTOR = _HASHSEEDS,
  __module__ = 'hash_seeds_pb2'
  # @@protoc_insertion_point(class_scope:HashSeeds)
  ))
_sym_db.RegisterMessage(HashSeeds)


# @@protoc_insertion_point(module_scope)
