# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: per-session-info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16per-session-info.proto\"#\n\x0ePerSessionInfo\x12\x11\n\trelay_url\x18\x01 \x02(\t')



_PERSESSIONINFO = DESCRIPTOR.message_types_by_name['PerSessionInfo']
PerSessionInfo = _reflection.GeneratedProtocolMessageType('PerSessionInfo', (_message.Message,), {
  'DESCRIPTOR' : _PERSESSIONINFO,
  '__module__' : 'per_session_info_pb2'
  # @@protoc_insertion_point(class_scope:PerSessionInfo)
  })
_sym_db.RegisterMessage(PerSessionInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSESSIONINFO._serialized_start=26
  _PERSESSIONINFO._serialized_end=61
# @@protoc_insertion_point(module_scope)
