# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: periodic-info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13periodic-info.proto\"b\n\x0cPeriodicInfo\x12\x16\n\x0egame_server_ip\x18\x01 \x02(\t\x12\n\n\x02\x66\x32\x18\x02 \x01(\r\x12\n\n\x02\x66\x33\x18\x03 \x01(\r\x12\n\n\x02\x66\x34\x18\x04 \x01(\r\x12\n\n\x02\x66\x35\x18\x05 \x01(\r\x12\n\n\x02\x66\x36\x18\x06 \x01(\r\"-\n\rPeriodicInfos\x12\x1c\n\x05infos\x18\x01 \x03(\x0b\x32\r.PeriodicInfo')



_PERIODICINFO = DESCRIPTOR.message_types_by_name['PeriodicInfo']
_PERIODICINFOS = DESCRIPTOR.message_types_by_name['PeriodicInfos']
PeriodicInfo = _reflection.GeneratedProtocolMessageType('PeriodicInfo', (_message.Message,), {
  'DESCRIPTOR' : _PERIODICINFO,
  '__module__' : 'periodic_info_pb2'
  # @@protoc_insertion_point(class_scope:PeriodicInfo)
  })
_sym_db.RegisterMessage(PeriodicInfo)

PeriodicInfos = _reflection.GeneratedProtocolMessageType('PeriodicInfos', (_message.Message,), {
  'DESCRIPTOR' : _PERIODICINFOS,
  '__module__' : 'periodic_info_pb2'
  # @@protoc_insertion_point(class_scope:PeriodicInfos)
  })
_sym_db.RegisterMessage(PeriodicInfos)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERIODICINFO._serialized_start=23
  _PERIODICINFO._serialized_end=121
  _PERIODICINFOS._serialized_start=123
  _PERIODICINFOS._serialized_end=168
# @@protoc_insertion_point(module_scope)
