# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structured_events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17structured_events.proto\"4\n\x1aSaveStructuredEventRequest\x12\x16\n\x0esequenceNumber\x18\x01 \x01(\r\"5\n\x1bSaveStructuredEventResponse\x12\x16\n\x0esequenceNumber\x18\x01 \x01(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'structured_events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SAVESTRUCTUREDEVENTREQUEST._serialized_start=27
  _SAVESTRUCTUREDEVENTREQUEST._serialized_end=79
  _SAVESTRUCTUREDEVENTRESPONSE._serialized_start=81
  _SAVESTRUCTUREDEVENTRESPONSE._serialized_end=134
# @@protoc_insertion_point(module_scope)
