# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tcp-node-msgs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13tcp-node-msgs.proto\"\xdf\x01\n\x12SocialPlayerAction\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12\x14\n\x0cto_player_id\x18\x02 \x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\x03\x12\x11\n\tfirstName\x18\x04 \x01(\t\x12\x10\n\x08lastName\x18\x05 \x01(\t\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x07 \x01(\t\x12\x13\n\x0b\x63ountryCode\x18\x08 \x01(\x05\x12\x10\n\x08\x66lagType\x18\t \x01(\x03\x12\x0e\n\x06mgType\x18\n \x01(\x03\x12\x15\n\reventSubgroup\x18\x0b \x01(\x03')



_SOCIALPLAYERACTION = DESCRIPTOR.message_types_by_name['SocialPlayerAction']
SocialPlayerAction = _reflection.GeneratedProtocolMessageType('SocialPlayerAction', (_message.Message,), {
  'DESCRIPTOR' : _SOCIALPLAYERACTION,
  '__module__' : 'tcp_node_msgs_pb2'
  # @@protoc_insertion_point(class_scope:SocialPlayerAction)
  })
_sym_db.RegisterMessage(SocialPlayerAction)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOCIALPLAYERACTION._serialized_start=24
  _SOCIALPLAYERACTION._serialized_end=247
# @@protoc_insertion_point(module_scope)
