# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_storage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_storage.proto\"3\n\x0bUserStorage\x12$\n\rgame_settings\x18\x02 \x01(\x0b\x32\r.GameSettings\"(\n\x0cGameSettings\x12\x18\n\x03\x66\x32\x32\x18\x16 \x01(\x0b\x32\x0b.Attributes\"T\n\nAttributes\x12\n\n\x02\x66\x32\x18\x02 \x01(\x02\x12\n\n\x02\x66\x33\x18\x03 \x01(\x05\x12\n\n\x02\x66\x34\x18\x04 \x01(\x05\x12\n\n\x02\x66\x35\x18\x05 \x01(\x05\x12\n\n\x02\x66\x36\x18\x06 \x01(\x05\x12\n\n\x02\x66\x37\x18\x07 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_storage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERSTORAGE._serialized_start=22
  _USERSTORAGE._serialized_end=73
  _GAMESETTINGS._serialized_start=75
  _GAMESETTINGS._serialized_end=115
  _ATTRIBUTES._serialized_start=117
  _ATTRIBUTES._serialized_end=201
# @@protoc_insertion_point(module_scope)
