# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: variants.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evariants.proto\"7\n\x07Variant\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x01(\r\x12\x0f\n\x02\x66\x33\x18\x03 \x03(\x0b\x32\x03.M3\"&\n\x08Variants\x12\x1a\n\x08variants\x18\x01 \x03(\x0b\x32\x08.Variant\"\x15\n\x02M3\x12\x0f\n\x02\x66\x31\x18\x01 \x03(\x0b\x32\x03.M1\"#\n\x02M1\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x02\x66\x32\x18\x02 \x03(\x0b\x32\x03.M2\"\x10\n\x02M2\x12\n\n\x02\x66\x34\x18\x04 \x02(\r')



_VARIANT = DESCRIPTOR.message_types_by_name['Variant']
_VARIANTS = DESCRIPTOR.message_types_by_name['Variants']
_M3 = DESCRIPTOR.message_types_by_name['M3']
_M1 = DESCRIPTOR.message_types_by_name['M1']
_M2 = DESCRIPTOR.message_types_by_name['M2']
Variant = _reflection.GeneratedProtocolMessageType('Variant', (_message.Message,), {
  'DESCRIPTOR' : _VARIANT,
  '__module__' : 'variants_pb2'
  # @@protoc_insertion_point(class_scope:Variant)
  })
_sym_db.RegisterMessage(Variant)

Variants = _reflection.GeneratedProtocolMessageType('Variants', (_message.Message,), {
  'DESCRIPTOR' : _VARIANTS,
  '__module__' : 'variants_pb2'
  # @@protoc_insertion_point(class_scope:Variants)
  })
_sym_db.RegisterMessage(Variants)

M3 = _reflection.GeneratedProtocolMessageType('M3', (_message.Message,), {
  'DESCRIPTOR' : _M3,
  '__module__' : 'variants_pb2'
  # @@protoc_insertion_point(class_scope:M3)
  })
_sym_db.RegisterMessage(M3)

M1 = _reflection.GeneratedProtocolMessageType('M1', (_message.Message,), {
  'DESCRIPTOR' : _M1,
  '__module__' : 'variants_pb2'
  # @@protoc_insertion_point(class_scope:M1)
  })
_sym_db.RegisterMessage(M1)

M2 = _reflection.GeneratedProtocolMessageType('M2', (_message.Message,), {
  'DESCRIPTOR' : _M2,
  '__module__' : 'variants_pb2'
  # @@protoc_insertion_point(class_scope:M2)
  })
_sym_db.RegisterMessage(M2)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VARIANT._serialized_start=18
  _VARIANT._serialized_end=73
  _VARIANTS._serialized_start=75
  _VARIANTS._serialized_end=113
  _M3._serialized_start=115
  _M3._serialized_end=136
  _M1._serialized_start=138
  _M1._serialized_end=173
  _M2._serialized_start=175
  _M2._serialized_end=191
# @@protoc_insertion_point(module_scope)
