# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zfiles.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0czfiles.proto\"Y\n\nZFileProto\x12\n\n\x02id\x18\x01 \x02(\x04\x12\x0e\n\x06\x66older\x18\x02 \x02(\t\x12\x10\n\x08\x66ilename\x18\x03 \x02(\t\x12\n\n\x02\x66\x34\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x02(\x04\"*\n\x0bZFilesProto\x12\x1b\n\x06zfiles\x18\x01 \x03(\x0b\x32\x0b.ZFileProto')



_ZFILEPROTO = DESCRIPTOR.message_types_by_name['ZFileProto']
_ZFILESPROTO = DESCRIPTOR.message_types_by_name['ZFilesProto']
ZFileProto = _reflection.GeneratedProtocolMessageType('ZFileProto', (_message.Message,), {
  'DESCRIPTOR' : _ZFILEPROTO,
  '__module__' : 'zfiles_pb2'
  # @@protoc_insertion_point(class_scope:ZFileProto)
  })
_sym_db.RegisterMessage(ZFileProto)

ZFilesProto = _reflection.GeneratedProtocolMessageType('ZFilesProto', (_message.Message,), {
  'DESCRIPTOR' : _ZFILESPROTO,
  '__module__' : 'zfiles_pb2'
  # @@protoc_insertion_point(class_scope:ZFilesProto)
  })
_sym_db.RegisterMessage(ZFilesProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ZFILEPROTO._serialized_start=16
  _ZFILEPROTO._serialized_end=105
  _ZFILESPROTO._serialized_start=107
  _ZFILESPROTO._serialized_end=149
# @@protoc_insertion_point(module_scope)
